name: Build Image and Artifact
description: Common steps to deploy a built docker image to a target environment
inputs:
  dockerTag:
    description: The Tag that is being deployed
    required: true
  serviceName:
    description: The Service name that is being updated
    required: true
  cfAPIKey:
    description: The Codefresh API key for auth
    required: true
  cfTriggerName:
    description: The name of the trigger in Codefresh pipeline to use
    required: true
  cfPipelineName:
    description: The Pipeline in codefresh that is being ran
    required: true
  cfPipelineBranch:
    description: The Branch to use to run the pipeline
    required: true
  targetEnv:
    description: What environment is being targeted
    required: true
  testsVersion:
    description: The versions of the tests to run
    required: false
runs:
  using: composite
  steps:
    - name: 'Decide what trigger to run, dev-cdk or dev-aic'
      shell: bash
      run: |
        # Check if the OB or Core functional tests are being ran
        if [ "${{ inputs.cfPipelineName }}" == "SAPIG-devenv/dev-cdk-ob-functional-tests" ]; then
          # Check if the target env is dev-cdk or dev-aic
          if [ "${{ inputs.targetEnv }}" == "dev-aic" ]; then
            echo "cfPipelineName=SAPIG-devenv/dev-aic-ob-functional-tests" >> ${GITHUB_ENV}
            echo "cfPipelineBranch=master" >> ${GITHUB_ENV}
          else
            echo "cfPipelineName=${{ inputs.cfPipelineName }}" >> ${GITHUB_ENV}
            echo "cfPipelineBranch=${{ inputs.cfPipelineBranch }}" >> ${GITHUB_ENV}
          fi
        else
          if [ "${{ inputs.targetEnv }}" == "dev-aic" ]; then
            echo "cfPipelineName=SAPIG-devenv/dev-aic-core-functional-tests" >> ${GITHUB_ENV}
            echo "cfPipelineBranch=master" >> ${GITHUB_ENV}
          else
            echo "cfPipelineName=${{ inputs.cfPipelineName }}" >> ${GITHUB_ENV}
            echo "cfPipelineBranch=${{ inputs.cfPipelineBranch }}" >> ${GITHUB_ENV}
          fi        
        fi
        # If version contains a ',' then its likely come from a GitHub build and we want to remove it
        if [[ "${{ inputs.testsVersion }}" == *","* ]]; then
          updatedVersion=$(echo "${{ inputs.testsVersion }}" | sed "s/,/ /")
          echo "version=$updatedVersion" >> ${GITHUB_ENV}
        else
        else
          echo "version=${{ inputs.testsVersion }}" >> ${GITHUB_ENV}
        fi
    - name: 'Run Functional Tests'
      uses: codefresh-io/codefresh-pipeline-runner@master
      with:
        args: '-v IMAGE_REPO=securebanking/${{ inputs.serviceName }} -v TAG=${{ inputs.dockerTag }} -v TEST_TASK=${{ env.version }} -v BRANCH=${{ env.cfPipelineBranch }}'
      env:
        PIPELINE_NAME: ${{ env.cfPipelineName }}
        CF_API_KEY: ${{ inputs.cfAPIKey }}
        TRIGGER_NAME: ${{ inputs.cfTriggerName }}
        CF_BRANCH: ${{ env.cfPipelineBranch }}