name: Set Maven Config
description: Action to create a maven config file during workflow
inputs:
  javaDistribution:
    description: What java distribution to use
    required: true
  javaVersion:
    description: What java version to use
    required: true
  javaArchitecture:
    description: What java architecture to use
    required: true
  cache:
    description: What cache to use
    required: false
runs:
  using: composite
  steps:
    - name: Set Cache with Community Repository
      uses: actions/setup-java@v4
      continue-on-error: true
      with:
        distribution: ${{ inputs.javaDistribution }}
        java-version: ${{ inputs.javaVersion }}
        architecture: ${{ inputs.javaArchitecture }}
        cache: ${{ inputs.cache || null }}
    - name: Move Settings.xml
      if: always()
      shell: bash
      run: |
        mkdir -p /home/runner/.m2
        ls -la
        mv secure-api-gateway-ci/maven/settings.xml /home/runner/.m2/ || mv maven/settings.xml /home/runner/.m2/