name: Set Maven Config
description: Action to create a maven config file during workflow
inputs:
  javaDistribution:
    description: What java distribution to use
    required: true
  javaVersion:
    description: What java version to use
    required: true
  javaArchitecture:
    description: What java architecture to use
    required: true
  cache:
    description: What cache to use
    required: true
  mavenServerID:
    description: What Server to connect too
    required: true
runs:
  using: composite
  steps:
    - name: Set Cache with Community Repository
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.javaDistribution }}
        java-version: ${{ inputs.javaVersion }}
        architecture: ${{ inputs.javaArchitecture }}
        cache: ${{ inputs.cache }}
    - name: Move Settings.xml
      shell: bash
      run: |
        mkdir -p /home/runner/.m2
        mv secure-api-gateway-ci/maven/settings.xml /home/runner/.m2/