name: Build Image
inputs:
  repositoryName: 
    required: true
    type: string
  dockerBuildCommands:
    required: true
    type: string
  FR_ARTIFACTORY_USER:
    required: true
    type: string
  FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with: 
        repository: SecureApiGateway/${{ inputs.repositoryName }}
        path: ${{ inputs.repositoryName }}
    - name: Run Docker Commands
      shell: bash
      run: |
        cd ${{ inputs.repositoryName }}
        ${{ inputs.dockerBuildCommands }}