name: Build Artifact
description: Common steps to build a Maven artifact
inputs:
  checkoutBranch:
    description: What branch of the repo to checkout
    required: false
  checkoutCode:
    description: Wherever or not to checkout the code for the repo
    required: true
  FR_ARTIFACTORY_USER:
    description: What user to use to auth to Maven Server
    required: true
  FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD:
    description: What user password to use to auth to Maven Server
    required: true
  mavenBuildCommands:
    description: The maven commands to be ran to product the artifact
    required: true
  repositoryName:
    description: The repository name to checkout
    required: true
  updateMavenServer:
    description: Wherever or not the maven server should try get updated
    required: true
runs:
  using: composite
  steps:
    - name: Determine what Branch of code to check out
      shell: bash
      run: |
        if [ ${{ inputs.checkoutCode }} == 'true' ]; then
          if [[ "${{ inputs.checkoutBranch }}" != "master" || "${{ inputs.checkoutBranch }}" != "main" ]]; then
            echo CHECKOUTBRANCHCODE=true >> ${GITHUB_ENV}
          else
            echo CHECKOUTMAINCODE=true >> ${GITHUB_ENV}
          fi
        else
          echo CHECKOUTMAINCODE=false >> ${GITHUB_ENV}
          echo CHECKOUTBRANCHCODE=false >> ${GITHUB_ENV}
        fi
    - name: Checkout Main Branch Code
      uses: actions/checkout@v4
      if: env.CHECKOUTMAINCODE == 'true'
      with: 
        repository: ${{ inputs.repositoryName }}
        path: ${{ inputs.repositoryName }}
    - name: Checkout Branch Code
      uses: actions/checkout@v4
      if: env.CHECKOUTBRANCHCODE == 'true'
      with:
        repository: ${{ inputs.repositoryName }}
        path: ${{ inputs.repositoryName }}
        ref: ${{ inputs.checkoutBranch }}
    - name: Get Version
      shell: bash
      if: inputs.updateMavenServer == 'true'
      run: |
        echo "VERSION=$( cd ${{ inputs.repositoryName }} && mvn help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV
        echo "MAVEN_SERVER_COMMUNITY=maven.forgerock.org-community" >> $GITHUB_ENV
      env:
        FR_ARTIFACTORY_USER: ${{ inputs.FR_ARTIFACTORY_USER }}
        FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ inputs.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
    - name: Push to community snapshot if version contains snapshot
      if: contains( env.VERSION, 'SNAPSHOT')
      shell: bash
      run: |
        if [ ${{ inputs.updateMavenServer }} == 'true' ]; then
          echo "MAVEN_SERVER_COMMUNITY=maven.forgerock.org-community-snapshots" >> $GITHUB_ENV
        fi
    - name: Set Cache with Community Repository
      uses: actions/setup-java@v4
      if: inputs.updateMavenServer == 'true'
      with:
        distribution: 'zulu'
        java-version: '17'
        architecture: x64
        cache: 'maven'
        server-id: ${{ env.MAVEN_SERVER_COMMUNITY }} # community repo to publish the java artifact
        server-username: FR_ARTIFACTORY_USER # placeholder variable for username in deploy
        server-password: FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD # placeholder variable for token in deploy
    - name: Deploy Core Maven Artifact Package
      shell: bash
      run: |
        cd ${{ inputs.repositoryName }}
        ${{ inputs.mavenBuildCommands }}
      env:
        FR_ARTIFACTORY_USER: ${{ inputs.FR_ARTIFACTORY_USER }}
        FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ inputs.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}