name: Build Artifact
description: Common steps to build a Maven artifact
inputs:
  checkoutCode:
    description: Wherever or not to checkout the code for the repo
    required: true
  FR_ARTIFACTORY_REPO:
    description: What repo to push in the Maven Server
    required: true
  FR_ARTIFACTORY_USER:
    description: User to authenticate to Maven Server
    required: true
  FR_ARTIFACTORY_USER_ACCESS_TOKEN:
    description: What access token to use to push to the Maven Server
    required: true
  FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD:
    description: Password for User to authenticate to Maven Server
    required: true
  helmCreatePackageCommand:
    description: Command to run to create helm package
    required: true
  helmPublishPackageCommand:
    description: Command to run to publish helm package
    required: true
  repositoryName:
    description: The repository name to checkout
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      if: inputs.checkoutCode == 'true'
      with: 
        repository: ${{ inputs.repositoryName }}
        path: ${{ inputs.repositoryName }}
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        # JFrog platform url (for example: https://acme.jfrog.io)
        JF_URL: ${{ inputs.FR_ARTIFACTORY_REPO }}
        # JFrog Platform access token
        JF_ACCESS_TOKEN: ${{ inputs.FR_ARTIFACTORY_USER_ACCESS_TOKEN }}
    - name: Add Helm Repo
      shell: bash
      run: |
        helm repo add forgerock-helm https://maven.forgerock.org/artifactory/forgerock-helm-virtual/ --username ${{ inputs.FR_ARTIFACTORY_USER }} --password ${{ inputs.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
    - name: Create & Publish Helm Package
      shell: bash
      run: |
        cd ${{ inputs.repositoryName }}
        ${{ inputs.helmCreatePackageCommand }}
        ${{ inputs.helmPublishPackageCommand }}