name: Build Image and Artifact
description: Common steps to deploy a built docker image to a target environment
inputs:
  dockerTag:
    description: The Tag that is being deployed
    required: true
  serviceName:
    description: The Service name that is being updated
    required: true
  cfAPIKey:
    description: The Codefresh API key for auth
    required: true
  cfTriggerName:
    description: The name of the trigger in Codefresh pipeline to use
    required: true
  cfPipelineName:
    description: The Pipeline in codefresh that is being ran
    required: true
  cfPipelineBranch:
    description: The Branch to use to run the pipeline
    required: true
  sapigType:
    description: The Type of SAPIG that is being deployed, use BOTH for deployments that need to go to both
    required: true
runs:
  using: composite
  steps:
    - name: Create Lowercase Github Username
      shell: bash
      run: |
        echo "GITHUB_USER=$(echo ${{github.actor}} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}
        if [[ ${{ inputs.sapigType }} == "both" ]]; then
          echo DEPLOYOB=true >> ${GITHUB_ENV}
          echo DEPLOYCORE=true >> ${GITHUB_ENV}
        elif [[ ${{ inputs.sapigType }} == "ob" ]]; then
          echo DEPLOYOB=true >> ${GITHUB_ENV}
          echo DEPLOYCORE=false >> ${GITHUB_ENV}
        elif [[ ${{ inputs.sapigType }} == "core" ]]; then
          echo DEPLOYOB=false >> ${GITHUB_ENV}
          echo DEPLOYCORE=true >> ${GITHUB_ENV}
        elif [[ ${{ inputs.sapigType }} == "none" ]]; then
          echo DEPLOYOB=false >> ${GITHUB_ENV}
          echo DEPLOYCORE=false >> ${GITHUB_ENV}
        else
          echo "Unexpected value for sapigType, use 'ob','core','both' or 'none'"
        fi

    - name: 'Update OB Environment'
      uses: codefresh-io/codefresh-pipeline-runner@master
      if: env.DEPLOYOB == 'true'
      with:
        args: '-v TAG=${{ inputs.dockerTag }} -v SERVICE_NAME=${{ inputs.serviceName }} -v ENVIRONMENT=${{ env.GITHUB_USER }}-ob'
      env:
        PIPELINE_NAME: SAPIG-devenv/dev-ob-service-build
        CF_API_KEY: ${{ inputs.cfAPIKey }}
        TRIGGER_NAME: ${{ inputs.cfTriggerName }}
        CF_BRANCH: ${{ inputs.cfPipelineBranch }}

    - name: 'Update Core Environment'
      uses: codefresh-io/codefresh-pipeline-runner@master
      if: env.DEPLOYCORE == 'true'
      with:
        args: '-v TAG=${{ inputs.dockerTag }} -v SERVICE_NAME=${{ inputs.serviceName }} -v ENVIRONMENT=${{ env.GITHUB_USER }}-core'
      env:
        PIPELINE_NAME: SAPIG-devenv/dev-core-service-build
        CF_API_KEY: ${{ inputs.cfAPIKey }}
        TRIGGER_NAME: ${{ inputs.cfTriggerName }}
        CF_BRANCH: ${{ inputs.cfPipelineBranch }}