name: Code Scanning
description: Common steps to perform a code scan on a components
inputs:
  cache:
    description: What cache to use
    required: true
  checkoutCode:
    description: Wherever or not to checkout the code for the repo
    required: true
  FR_ARTIFACTORY_USER:
    description: What user to use to auth to Maven Server
    required: true
  FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD:
    description: What user password to use to auth to Maven Server
    required: true
  javaArchitecture:
    description: What java architecture to use
    required: true
  javaDistribution:
    description: What java distribution to use
    required: true
  javaVersion:
    description: What java version to use
    required: true
  language:
    description: The language to use for the scanning
    required: true
  mavenServerID:
    description: What Server to connect too
    required: true
  repositoryName:
    description: The repository name to checkout
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      if: inputs.checkoutCode == 'true'
      with: 
        repository: ${{ inputs.repositoryName }}
        path: ${{ inputs.repositoryName }}
    # Set Maven Config
    - name: Set Maven Config
      uses: ./secure-api-gateway-ci/.github/actions/set-maven-config
      with:
        cache: ${{ inputs.cache }}
        javaArchitecture: ${{ inputs.javaArchitecture }}
        javaDistribution: ${{ inputs.javaDistribution }}
        javaVersion: ${{ inputs.javaVersion }}
        mavenServerID: ${{ inputs.mavenServerID }}
        repositoryName: ${{ inputs.repositoryName }}
        updateMavenServer: false
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ inputs.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
      with:
        working-directory: ${{ inputs.repositoryName }}
      env:
        FR_ARTIFACTORY_USER: ${{ inputs.FR_ARTIFACTORY_USER }}
        FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ inputs.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ inputs.language }}"