name: Code Scanning
description: Common steps to perform a code scan on a components
inputs:
  actionTrigger:
    description: Action performed will decide what steps to use
    required: true
  cache:
    description: What cache to use
    required: true
  checkoutBranch:
    description: What branch of the repo to checkout
    required: false
  checkoutCode:
    description: Wherever or not to checkout the code for the repo
    required: true
  FR_ARTIFACTORY_USER:
    description: What user to use to auth to Maven Server
    required: true
  FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD:
    description: What user password to use to auth to Maven Server
    required: true
  javaArchitecture:
    description: What java architecture to use
    required: true
  javaDistribution:
    description: What java distribution to use
    required: true
  javaVersion:
    description: What java version to use
    required: true
  language:
    description: The language to use for the scanning
    required: true
  repositoryName:
    description: The repository name to checkout
    required: true
runs:
  using: composite
  steps:
    - name: Determine what Branch of code to check out
      shell: bash
      run: |
        if [ ${{ inputs.checkoutCode }} == 'true' ]; then
          if [[ "${{ inputs.checkoutBranch }}" != "master" || "${{ inputs.checkoutBranch }}" != "main" ]]; then
            echo CHECKOUTBRANCHCODE=true >> ${GITHUB_ENV}
          else
            echo CHECKOUTMAINCODE=true >> ${GITHUB_ENV}
          fi
        else
          echo CHECKOUTMAINCODE=false >> ${GITHUB_ENV}
          echo CHECKOUTBRANCHCODE=false >> ${GITHUB_ENV}
        fi
    - name: Checkout Main Branch Code
      uses: actions/checkout@v4
      if: env.CHECKOUTMAINCODE == 'true'
      with:
        repository: ${{ inputs.repositoryName }}
        path: ${{ inputs.repositoryName }}
    - name: Checkout Branch Code
      uses: actions/checkout@v4
      if: env.CHECKOUTBRANCHCODE == 'true'
      with:
        repository: ${{ inputs.repositoryName }}
        path: ${{ inputs.repositoryName }}
        ref: ${{ inputs.checkoutBranch }}
    # Set Maven Config
    - name: Set Maven Config
      uses: ./secure-api-gateway-ci/.github/actions/set-maven-config
      if: inputs.actionTrigger == 'merge'
      with:
        cache: ${{ inputs.cache }}
        javaArchitecture: ${{ inputs.javaArchitecture }}
        javaDistribution: ${{ inputs.javaDistribution }}
        javaVersion: ${{ inputs.javaVersion }}
    # Set Maven Config
    - name: Set Maven Config
      uses: ./.github/actions/set-maven-config
      if: inputs.actionTrigger == 'nightly'
      with:
        cache: ${{ inputs.cache }}
        javaArchitecture: ${{ inputs.javaArchitecture }}
        javaDistribution: ${{ inputs.javaDistribution }}
        javaVersion: ${{ inputs.javaVersion }}
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ inputs.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
      with:
        working-directory: ${{ inputs.repositoryName }}
      env:
        FR_ARTIFACTORY_USER: ${{ inputs.FR_ARTIFACTORY_USER }}
        FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ inputs.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ inputs.language }}"