name: Authentication
description: Common commands used to auth to services during workflows
inputs:
  garKey:
    description: The GCP Json Auth Key
    required: true
  garLocation:
    description: The location of the Google Artifact Registry
    required: true

runs:
  using: composite
  steps:
    # Auth GCP, SDK & Artifact Registry
    - name: Auth to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.garKey }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
    - name: Auth Docker
      shell: bash
      run: |
        gcloud auth configure-docker ${{ inputs.garLocation }}
