name: Build Image and Artifact
description: Common steps to deploy a built docker image to a target environment
inputs:
  dockerTag:
    description: The Tag that is being deployed
    required: true
  serviceName:
    description: The Service name that is being updated
    required: true
  cfAPIKey:
    description: The Codefresh API key for auth
    required: true
  cfTriggerName:
    description: The name of the trigger in Codefresh pipeline to use
    required: true
  cfPipelineName:
    description: The Pipeline in codefresh that is being ran
    required: true
  cfPipelineBranch:
    description: The Branch to use to run the pipeline
    required: true
  sortCFTrigger:
    description: Wherever or not to apply logic to the trigger
    required: false
runs:
  using: composite
  steps:
    - name: 'Decide what trigger to run, dev or nightly'
      if: inputs.sortCFTrigger == 'true'
      shell: bash
      run: |
        # If the docker tag to run contains v# then it is a dev target
        if [[ "${{ inputs.dockerTag }}" =~ v[0-9] ]]; then
          echo "cfPipelineName=${{ inputs.cfPipelineName }}" >> ${GITHUB_ENV}
        else
          # If it doesn't contain V# then it is a nightly target
          echo "cfPipelineName=SAPIG-devenv/nightly-ob-dcr-conformance-tests" >> ${GITHUB_ENV}
        fi
    - name: 'Run Conformance DCR Tests'
      uses: codefresh-io/codefresh-pipeline-runner@master
      with:
        args: '-v IMAGE_REPO=europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/${{ inputs.serviceName }} -v TAG=${{ inputs.dockerTag }}'
      env:
        PIPELINE_NAME: ${{ env.cfPipelineName || inputs.cfPipelineName }}
        CF_API_KEY: ${{ inputs.cfAPIKey }}
        TRIGGER_NAME: ${{ inputs.cfTriggerName }}
        CF_BRANCH: ${{ inputs.cfPipelineBranch }}
