name: Build Conformance DCR
description: Common steps to build the conformance dcr project
runs:
  using: docker
  image: golang:1.17-alpine3.15
  steps:
    - name: Install packages
      run: |
        apk update && apk add git make bash curl
    - name: Make Tools
      run: |
        make tools
    - name: Build
      run: |
        make build
    - name: Test
      run: |
        make test