name: Nightly Check
on:
  schedule:
    - cron: '0 2 * * 1-5' # UTC
  workflow_dispatch:
jobs:
  copyright:
    name: Copyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CI Code
        uses: actions/checkout@v4
      - name: Call check copyright for RS
        uses: ./.github/actions/check-copyright
        with:
          checkoutCode: true
          repositoryName: SecureApiGateway/secure-api-gateway-ob-uk-rs
      - name: Call check copyright for RCS
        uses: ./.github/actions/check-copyright
        with:
          checkoutCode: true
          repositoryName: SecureApiGateway/secure-api-gateway-ob-uk-rcs
  analyze-core:
    name: Analyze Core
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
    steps:
      - name: Checkout CI Code
        uses: actions/checkout@v4
      - name: Call code-scanning on Core
        uses: ./.github/actions/code-scanning
        with:
          cache: 'maven'
          checkoutCode: true
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
          githubAction: nightly
          javaArchitecture: x64
          javaDistribution: 'zulu'
          javaVersion: '17'
          language: 'java-kotlin'
          mavenServerID: 'forgerock-internal-releases'
          repositoryName: SecureApiGateway/secure-api-gateway-core
  analyze-common:
    name: Analyze Common
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
    steps:
      - name: Checkout CI Code
        uses: actions/checkout@v4
      - name: Call code-scanning on Core
        uses: ./.github/actions/code-scanning
        with:
          cache: 'maven'
          checkoutCode: true
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
          githubAction: nightly
          javaArchitecture: x64
          javaDistribution: 'zulu'
          javaVersion: '17'
          language: 'java-kotlin'
          mavenServerID: 'forgerock-internal-releases'
          repositoryName: SecureApiGateway/secure-api-gateway-ob-uk-common
  analyze-rs:
    name: Analyze RS
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
    steps:
      - name: Checkout CI Code
        uses: actions/checkout@v4
      - name: Call code-scanning on Core
        uses: ./.github/actions/code-scanning
        with:
          cache: 'maven'
          checkoutCode: true
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
          githubAction: nightly
          javaArchitecture: x64
          javaDistribution: 'zulu'
          javaVersion: '17'
          language: 'java-kotlin'
          mavenServerID: 'forgerock-internal-releases'
          repositoryName: SecureApiGateway/secure-api-gateway-ob-uk-rs
  analyze-rcs:
    name: Analyze RCS
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
    steps:
      - name: Checkout CI Code
        uses: actions/checkout@v4
      - name: Call code-scanning on Core
        uses: ./.github/actions/code-scanning
        with:
          cache: 'maven'
          checkoutCode: true
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}
          githubAction: nightly
          javaArchitecture: x64
          javaDistribution: 'zulu'
          javaVersion: '17'
          language: 'java-kotlin'
          mavenServerID: 'forgerock-internal-releases'
          repositoryName: SecureApiGateway/secure-api-gateway-ob-uk-rcs