name: Pull Request - Build and Deploy
on:
  workflow_call:
    inputs:
      componentName:
        required: true
        type: string
      prNumber:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      # Checkout CI Repo
      - name: Checkout CI Repo
        uses: actions/checkout@v4
        with:
          repository: SecureApiGateway/secure-api-gateway-ci
          ref: 1389-standard-steps-for-workflows # Remove when done testing
          path: secure-api-gateway-ci
      # Checkout Calling Repo
      - name: Checkout Calling Repo
        uses: actions/checkout@v4
        with:
          repository: SecureApiGateway/${{ inputs.componentName }}
          ref: 1389-standard-steps-for-workflows # Remove when done testing
          path: ${{ inputs.componentName }}
      # Prepare Environment
      - name: Prepare Environment
        run: |
          grep -v '^#' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env >> $GITHUB_ENV
      # Auth GCP, SDK & Artifact Registry
      - name: Authentication
        uses: ./secure-api-gateway-ci/.github/actions/authentication
        if: env.STEPS_AUTHENTICATE == 'true'
        with:
          garKey: ${{ secrets.DEV_GAR_KEY }}
          garLocation: ${{ env.GAR_LOCATION }}
      # Set Maven Config
      - name: Set Maven Config
        uses: ./secure-api-gateway-ci/.github/actions/set-maven-config
        if: env.STEPS_SET_MAVEN_CONFIG == 'true'
        with:
          javaDistribution: ${{ env.JAVA_DISTRIBUTION }}
          javaVersion: ${{ env.JAVA_VERSION }}
          javaArchitecture: ${{ env.JAVA_ARCHITECTURE }}
          cache: ${{ env.CACHE }}
          mavenServerID: ${{ env.MAVEN_SERVER_ID }}
      # Builds Docker Image
      - name: Build Image
        uses: ./secure-api-gateway-ci/.github/actions/build-image
        if: env.STEPS_BUILD_DOCKER_IMAGE == 'true'
        with:
          checkoutCode: false
          repositoryName: ${{ inputs.componentName }}
          dockerBuildCommands: "make clean && make docker tag=${{ inputs.prNumber }} env=dev && make docker tag=${{ inputs.prNumber }}-prod"
          FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
          FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    steps:
      # Checkout CI Repo
      - name: Checkout CI Repo
        uses: actions/checkout@v4
        with:
          repository: SecureApiGateway/secure-api-gateway-ci
          ref: 1389-standard-steps-for-workflows # Remove when done testing
          path: secure-api-gateway-ci
      # Checkout Calling Repo
      - name: Checkout Calling Repo
        uses: actions/checkout@v4
        with:
          repository: SecureApiGateway/${{ inputs.componentName }}
          ref: 1389-standard-steps-for-workflows # Remove when done testing
          path: ${{ inputs.componentName }}
      # Prepare Environment
      - name: Prepare Environment
        run: |
          grep -v '^#' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env >> $GITHUB_ENV
      - name: Call deploy-to-env
        uses: ./secure-api-gateway-ci/.github/actions/deploy-to-env
        if: env.STEPS_DEPLOY_CHANGES == 'true'
        with:
          prNumber: ${{ inputs.prNumber }}
          serviceName: ${{ env.SERVICE_NAME }}
          cfAPIKey: ${{ secrets.CF_API_KEY }}
          cfTriggerName: ${{ env.CF_TRIGGER_NAME }}
          cfPipelineName: ${{ env.CF_PIPELINE_NAME }}
          cfPipelineBranch: ${{ env.CF_PIPELINE_BRANCH }}