name: Pull Request Build and Deploy
on:
  workflow_call:
    inputs:
      componentName:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout CI Repo
        uses: actions/checkout@v4
      # Prepare Environment
      - name: Prepare Environment
        run: |
          grep -v '^#' secure-api-gateway-ci/component-config/${{ inputs.componentName }}.env >> $GITHUB_ENV
      # Checkout Calling Repo

      # Auth GCP, SDK & Artifact Registry
      - name: Authentication
        uses: ./.github/actions/authentication
        if: env.STEPS_AUTHENTICATE == 'true'
        with:
          garKey: ${{ secrets.DEV_GAR_KEY }}
          garLocation: ${{ env.GAR_LOCATION }}
      - name: Set Maven Config
        uses: ./.github/actions/set-maven-config
        if: env.STEPS_SET_MAVEN_CONFIG == 'true'
        with:
          javaDistribution: ${{ env.JAVA_DISTRIBUTION }}
          javaVersion: ${{ env.JAVA_VERSION }}
          javaArchitecture: ${{ env.JAVA_ARCHITECTURE }}
          cache: ${{ env.CACHE }}
          mavenServerID: ${{ env.MAVEN_SERVER_ID }}
      #- name: Build Image
      #  uses: ./.github/actions/build-image
      #  if: env.STEPS_BUILD_DOCKER_IMAGE == 'true'
      #  with:
      #    repositoryName: ${{ github.repository }}
      #    dockerBuildCommands: "make clean && make docker tag=$PR_NUMBER env=dev && make docker tag=$PR_NUMBER-prod"
      #    FR_ARTIFACTORY_USER: ${{ secrets.FR_ARTIFACTORY_USER }}
      #    FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD: ${{ secrets.FR_ARTIFACTORY_USER_ENCRYPTED_PASSWORD }}

#  deploy:
#    runs-on: ubuntu-latest
#    name: Deploy
#    needs: build
#    steps:
#      - name: Checkout CI Code
#        uses: actions/checkout@v4
#        with:
#          repository: SecureApiGateway/secure-api-gateway-ci
#          ref: 1389-standard-steps-for-workflows # To be removed after testing
#      - name: Call deploy-to-env
#        uses: ./.github/actions/deploy-to-env
#        with:
#          prNumber: ${{ env.PR_NUMBER }}
#          serviceName: ${{ env.SERVICE_NAME }}
#          cfAPIKey: ${{ secrets.CF_API_KEY }}
#          cfTriggerName: ${{ env.CF_TRIGGER_NAME }}
#          cfPipelineName: ${{ env.CF_PIPELINE_NAME }}
#          cfPipelineBranch: ${{ env.CF_PIPELINE_BRANCH }}